- hosts: frontends
  gather_facts: false
  tasks:
  # - name: Use Uri module for wrting smoke test.
  # - name: Fail if 'Ansible has done its job' is not in the page content
  - name: Curl website
    uri:
      url: "http://frontend1-{{}}"
      return_content: yes
    loop: "{{openstack_info.ansible_facts.openstack_servers}}"
    register: haproxy_status
    tags:
      - aws.smoke
  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in haproxy_status.content"
    tags:
      - aws.smoke
