---
# vars file for osp.servers
# osp_servers:
#   frontend:
#     name: frontend
#     state: present
#     image: rhel-guest
#     key_name: ansible_ssh
#     flavor: m2.small
#     security_group: frontend
#     meta:
#       - { group: frontends, deployment_name: QA}
#   app1:
#     name: app1
#     state: present
#     image: rhel-guest
#     key_name: ansible_ssh
#     flavor: m2.small
#     security_group: apps
#     meta:
#       - { group: apps, deployment_name: QA}
#   app2:
#     name: app2
#     state: present
#     image: rhel-guest
#     key_name: ansible_ssh
#     flavor: m2.small
#     security_group: apps
#     meta:
#       - { group: apps, deployment_name: QA}
#   db:
#     name: db
#     state: present
#     image: rhel-guest
#     key_name: ansible_ssh
#     flavor: m2.small
#     security_group: db
#     meta:
#       - { group: appdbs, deployment_name: QA}

instances:
  - name: app1
    metadata:
      group: apps
      deployment_name: QA
    flavor: m2.small
    keypair: ansible_ssh
    int_network: int_network
    ext_network: ext_network
    image: rhel-guest
    security_groups:
      - apps
  - name: app2
    metadata:
      group: apps
      deployment_name: QA
    flavor: m2.small
    keypair: ansible_ssh
    int_network: int_network
    ext_network: ext_network
    image: rhel-guest
    security_groups:
      - apps
  - name: db
    metadata:
      group: appsdb
      deployment_name: QA
    flavor: m2.small
    keypair: ansible_ssh
    int_network: int_network
    ext_network: ext_network
    image: rhel-guest
    security_groups:
      - db
  - name: frontend
    metadata:
      group: frontends
      deployment_name: QA
    flavor: m2.small
    keypair: ansible_ssh
    int_network: int_network
    ext_network: ext_network
    image: rhel-guest
    security_groups:
      - frontend
