---
# tasks file for lb-tier
- name: Install packages
  package:
    name: "{{ packages }}"
    state: present

- name: Disable Services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop: "{{ services }}"

- name: Remove haproxy config file
  file:
    state: absent
    dest: /etc/haproxy/haproxy.cfg

- name: Place haproxy config file
  template:
    src: ./haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart Services

- name: Enable Services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop: "{{ services }}"


- name: Confirm that HAProxy is working
  uri:
    url: "http://{{inventory_hostname}}"
    return_content: yes
  register: haproxy_status
  failed_when: "'Ansible has done its job' not in haproxy_status.content"
  ignore_errors: True