
- name: Remove ansible mark from ssh key file in ssh_key_data
  lineinfile:
      path: "{{user_cred_path}}"
      state: absent
      regexp: 'ANSIBLE MANAGED'

- name: Create Machine Credential to connect to workstation
  tower_credential:
    name: "{{ssh_cred_name}}"
    organization: "{{ org_name }}"
    state: present
    kind: ssh
    tower_host: "{{ tower_host_server }}"
    tower_username: "{{tower_user_name}}"
    tower_password: "{{tower_password}}"
    ssh_key_data: "{{user_cred_path}}"
    username: "{{user_cred_name}}"
    tower_verify_ssl: no

- name: Create Static Inventory
  tower_inventory:
    name: "{{static_inventory_name}}"
    organization: "{{ org_name }}"
    tower_host: "{{ tower_host_server }}"
    tower_username: "{{tower_user_name}}"
    tower_password: "{{tower_password}}"
    tower_verify_ssl: no

- name: Create Group in static inventory
  tower_group:
    inventory: "{{static_inventory_name}}"
    name: "{{group_name}}"
    organization: "{{ org_name }}"
    tower_host: "{{ tower_host_server }}"
    tower_username: "{{tower_user_name}}"
    tower_password: "{{tower_password}}"
    tower_verify_ssl: no

- name: Add workstation host to static inventory 
  tower_host:
    name: "{{host_name}}"
    inventory: "{{static_inventory_name}}"
    organization: "{{ org_name }}"
    tower_host: "{{ tower_host_server }}"
    tower_username: "{{tower_user_name}}"
    tower_password: "{{tower_password}}"
    tower_verify_ssl: no

- name: Associate workstation host to workstation group
  tower_group:
    inventory: "{{static_inventory_name}}"
    name: "{{group_name}}"
    organization: "{{ org_name }}"
    tower_host: "{{ tower_host_server }}"
    tower_username: "{{tower_user_name}}"
    tower_password: "{{tower_password}}"
    instance_filters: "name:workstation"
    tower_verify_ssl: no

- name: Create Tower Credential for opentlc
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: "{{ org_name }}"
    state: present
    kind: ssh
    tower_host: "{{ tower_host_server }}"
    tower_username: "{{tower_user_name}}"
    tower_password: "{{tower_password}}"
    tower_verify_ssl: no
    ssh_key_data: "{{opentlc_ssh_key}}"
    username: "{{ opentlc_login }}"

- name: Create Homework Assignment project 
  tower_project:
    name: "{{ proj_name }}"
    scm_branch: "{{ scm_branch }}"
    tower_password: "{{ tower_password }}"
    tower_host: "{{ tower_host_server }}"
    scm_credential: "{{ opentlc_cred_name }}"
    scm_clean: "yes"
    scm_url: "{{ scm_url }}"
    state: present
    scm_type: git
    scm_update_on_launch: "yes"
    tower_username: "{{ tower_user_name }}"
    organization: "{{ org_name }}"
    tower_verify_ssl: no

- name: Remove opentlc ssh key
  file:
    name: /root/secret.pem
    state: absent

