
# - name: Create workflow schema 
#   template:
#     src: workflow.j2
#     dest: /root/workflow.yml

- name: Create CI CD Workflow
  tower_workflow_template:
    name: "{{ workflow_template_name }}"
    organization: "{{ org_name }}"
    tower_host: "{{ tower_host_server }}"
    tower_username: "{{tower_user_name}}"
    tower_password: "{{tower_password}}"
    schema: "{{workflow_template}}"
    tower_verify_ssl: no

